name: Publish

on:
  release:
    types: [created,edited]

jobs:
  publish:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: ubuntu
            artifact_name: unisync
            asset_name: unisync-linux-amd64
          - os: windows-latest
            name: windows
            artifact_name: unisync.exe
            asset_name: unisync-windows-amd64.exe
          - os: macos-latest
            name: macos
            artifact_name: unisync
            asset_name: unisync-macos-amd64
          - os: ubuntu-latest
            name: openbsd
            artifact_name: unisync
            asset_name: unisync-openbsd-amd64
            goos: openbsd
            goarch: amd64
          - os: ubuntu-latest
            name: freebsd
            artifact_name: unisync
            asset_name: unisync-freebsd-amd64
            goos: freebsd
            goarch: amd64

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.3'
        check-latest: true
    - run: go build

    - uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        overwrite: true
